[2022-08-07 15:05:11,078] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: student_dag.load_to_postgres __airflow_temporary_run_2022-08-07T15:05:07.878883+00:00__ [queued]>
[2022-08-07 15:05:11,090] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: student_dag.load_to_postgres __airflow_temporary_run_2022-08-07T15:05:07.878883+00:00__ [queued]>
[2022-08-07 15:05:11,091] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-07 15:05:11,092] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-07 15:05:11,093] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-07 15:05:11,107] {taskinstance.py:1377} INFO - Executing <Task(customPostgresOperator): load_to_postgres> on 2022-08-01 00:00:00+00:00
[2022-08-07 15:05:11,113] {standard_task_runner.py:52} INFO - Started process 3957 to run task
[2022-08-07 15:05:11,117] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'student_dag', 'load_to_postgres', '__***_temporary_run_2022-08-07T15:05:07.878883+00:00__', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/students_dag.py', '--cfg-path', '/tmp/tmp5a79i9l7', '--error-file', '/tmp/tmpblf2bscu']
[2022-08-07 15:05:11,118] {standard_task_runner.py:80} INFO - Job 17: Subtask load_to_postgres
[2022-08-07 15:05:11,137] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-08-07 15:05:11,180] {task_command.py:369} INFO - Running <TaskInstance: student_dag.load_to_postgres __airflow_temporary_run_2022-08-07T15:05:07.878883+00:00__ [running]> on host 5cab04260180
[2022-08-07 15:05:11,272] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ankit
AIRFLOW_CTX_DAG_ID=student_dag
AIRFLOW_CTX_TASK_ID=load_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2022-08-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=__***_temporary_run_2022-08-07T15:05:07.878883+00:00__
[2022-08-07 15:05:11,280] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2022-08-07 15:05:11,285] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2022-08-07 15:05:21,233] {local_task_job.py:221} WARNING - State of this instance has been externally set to None. Terminating instance.
[2022-08-07 15:05:21,234] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 3957. PIDs of all processes in the group: [3957]
[2022-08-07 15:05:21,235] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 3957
[2022-08-07 15:05:21,291] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-08-07 15:05:21,301] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgresql" to address: Temporary failure in name resolution


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/plugins/Operators/postgresCustomOperator.py", line 15, in execute
    conn=customPostgresHook(self.conn_id).get_custom_connection()
  File "/opt/airflow/plugins/Hooks/postgresCustomHook.py", line 18, in get_custom_connection
    conn=db.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 142, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1543, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-08-07 15:05:21,311] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=student_dag, task_id=load_to_postgres, execution_date=20220801T000000, start_date=20220807T150511, end_date=20220807T150521
[2022-08-07 15:05:21,321] {standard_task_runner.py:97} ERROR - Failed to execute job 17 for task load_to_postgres ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(student_dag, load_to_postgres, __airflow_temporary_run_2022-08-07T15:05:07.878883+00:00__, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'load_to_postgres', 'dag_id': 'student_dag', 'run_id': '__airflow_temporary_run_2022-08-07T15:05:07.878883+00:00__', 'map_index': -1, 'start_date': datetime.datetime(2022, 8, 7, 15, 5, 11, 79349, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2022, 8, 7, 15, 5, 21, 310834, tzinfo=Timezone('UTC')), 'duration': 10}]
(Background on this error at: http://sqlalche.me/e/14/gkpj); 3957)
[2022-08-07 15:05:21,328] {process_utils.py:75} INFO - Process psutil.Process(pid=3957, status='terminated', exitcode=1, started='15:05:10') (3957) terminated with exit code 1
