[2022-08-07 14:30:27,507] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: student_dag.load_to_postgres manual__2022-08-07T14:30:23.245986+00:00 [queued]>
[2022-08-07 14:30:27,516] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: student_dag.load_to_postgres manual__2022-08-07T14:30:23.245986+00:00 [queued]>
[2022-08-07 14:30:27,517] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-07 14:30:27,517] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-07 14:30:27,517] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-07 14:30:27,534] {taskinstance.py:1377} INFO - Executing <Task(customPostgresOperator): load_to_postgres> on 2022-08-07 14:30:23.245986+00:00
[2022-08-07 14:30:27,539] {standard_task_runner.py:52} INFO - Started process 2289 to run task
[2022-08-07 14:30:27,542] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'student_dag', 'load_to_postgres', 'manual__2022-08-07T14:30:23.245986+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/students_dag.py', '--cfg-path', '/tmp/tmpde2t8an0', '--error-file', '/tmp/tmpb_ilwkt8']
[2022-08-07 14:30:27,543] {standard_task_runner.py:80} INFO - Job 5: Subtask load_to_postgres
[2022-08-07 14:30:27,592] {task_command.py:369} INFO - Running <TaskInstance: student_dag.load_to_postgres manual__2022-08-07T14:30:23.245986+00:00 [running]> on host 5cab04260180
[2022-08-07 14:30:27,657] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ankit
AIRFLOW_CTX_DAG_ID=student_dag
AIRFLOW_CTX_TASK_ID=load_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2022-08-07T14:30:23.245986+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-07T14:30:23.245986+00:00
[2022-08-07 14:30:27,658] {taskinstance.py:1889} ERROR - Task failed with exception
TypeError: execute() got an unexpected keyword argument 'context'
[2022-08-07 14:30:27,665] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=student_dag, task_id=load_to_postgres, execution_date=20220807T143023, start_date=20220807T143027, end_date=20220807T143027
[2022-08-07 14:30:27,675] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task load_to_postgres (execute() got an unexpected keyword argument 'context'; 2289)
[2022-08-07 14:30:27,714] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-07 14:30:27,743] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
